### ISSUE TITLE
OpenCore on Windows: MakeInstall.bat fails with file not found

### ISSUE THREAD

**Issue by F1Fan** [dortania/OpenCore-Desktop-Guide#34]
This is a little puzzling. The install USB disk did get created ok if I used the recovery option. However, since this type of Catalina install needs to download files from the web and I don't have a wired Ethernet connection available, I do need to have the full install option - not selecting the recovery option. 
The download of the install components (11 files) does complete with out any errors.
However, when running the MakeInstall.bat, I get the following as it attempts to create the USB:
Gathering DUET boot files...
 - boot
 - boot0af
 - boot1f32
Copying EFI folder to G:/EFI...
Copying boot to G:/boot...
Traceback (most recent call last):
  File "D:\Peter\Create USB\gibMacOS-master\MakeInstall.py", line 863, in <module>
    w.main()
  File "D:\Peter\Create USB\gibMacOS-master\MakeInstall.py", line 782, in main
    self.main()
  File "D:\Peter\Create USB\gibMacOS-master\MakeInstall.py", line 859, in main
    self.main()
  File "D:\Peter\Create USB\gibMacOS-master\MakeInstall.py", line 858, in main
    self.diskpart_erase(selected_disk, use_gpt, clover_version)
  File "D:\Peter\Create USB\gibMacOS-master\MakeInstall.py", line 290, in diskpart_erase
    self.select_package(disk, clover_version)
  File "D:\Peter\Create USB\gibMacOS-master\MakeInstall.py", line 386, in select_package
    self.dd_image(disk, os.path.join(temp, hfs), clover_version)
  File "D:\Peter\Create USB\gibMacOS-master\MakeInstall.py", line 424, in dd_image
    if clover_version == "OpenCore": self.install_oc(disk)
  File "D:\Peter\Create USB\gibMacOS-master\MakeInstall.py", line 496, in install_oc
    shutil.copy(os.path.join(temp,self.oc_boot),"{}/boot".format(part))
  File "C:\Users\Peter\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 415, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\Peter\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Peter\\AppData\\Local\\Temp\\tmp8i5kyuyb\\boot'
Looking at the temp folder, the boot folder is definitely not there.
By using  a Mac virtual machine, I can get the installation USB created.
The downside is that I have to switch between Windows and MacOS to complete the build - some utilities have to be run on the Windows environment to gather hardware-specific information for the config.plist build.
Any pointers will be very much appreciated.
Thanks ... Peter

**Comment by khronokernel** [comment]
Offline installs are only supported in macOS due to the HFS write support requirement, MakeInstall.bat only supports network installs as this avoid HFS.
Also issues for tools should be opened in their respective repo, I'm not the author of GibMacOS
